common: &common
  adapter: postgresql
  encoding: unicode
  username:
  password:

development:
  <<: *common
  database: tit
test:
  <<: *common
  database: tit_test
production:
  <<: *common
  database: tit_production
